name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        enable_ui: [on]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install 7-Zip
        run: choco install 7zip -y
        shell: pwsh

      - uses: seanmiddleditch/gha-setup-ninja@master

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Dependencies
        shell: pwsh
        run: |
          # 在 Windows 上安装所需的依赖项（如果有）
          # 例如，安装特定的库或工具
          Write-Output "No additional dependencies to install on Windows."

      - name: Generating Makefiles
        shell: pwsh
        run: |
          $enable_ccache = "off"
          Invoke-WebRequest -Uri "https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip" -OutFile "skia.zip"
          & "C:\Program Files\7-Zip\7z.exe" x skia.zip
          cmake -S . -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -DENABLE_UI=${{ matrix.enable_ui }} `
            -DENABLE_CCACHE=$enable_ccache `
            -DLAF_BACKEND=skia `
            -DSKIA_DIR=./skia `
            -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 `
            -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib

      - name: Compiling
        shell: pwsh
        run: |
          cd build
          ninja

      - uses: actions/upload-artifact@v3
        with:
          name: aseprite
          path: |
            build/bin/data
            build/bin/aseprite.exe
